

@baseUrl = http://localhost:4004


### test with one condition
POST {{baseUrl}}/rule/Rules
Content-Type: application/json

{
  "name": "Test Rule 3",
  "description": "Check BP name equals John",
  "targetEntity": "A_BusinessPartner",
  "conditions": [
    {
      "fieldName": "BusinessPartnerFullName",
      "operator": "=",
      "value": "John Doe",
      "binaryAnd": true
    }
  ]
}

### test with more than one condition
POST {{baseUrl}}/rule/Rules
Content-Type: application/json

{
  "name": "Test Rule 4",
  "description": "Check BP name and country",
  "targetEntity": "A_BusinessPartner",
  "conditions": [
    {
      "fieldName": "BusinessPartnerFullName",
      "operator": "contains",
      "value": "Corp",
      "binaryAnd": false
    },
    {
      "fieldName": "NameCountry",
      "operator": "=",
      "value": "US",
      "binaryAnd": true
    }
  ]
}

