@baseUrl=http://localhost:4004

###
# @name create_rule
POST {{baseUrl}}/rules/Rules
Content-Type: application/json

{
    "description":"my first rule",
    "andBinaryOperator":true,
    "entity_name":"A_AddressEmailAddress",
    "entity_service_name":"BusinessPartnerService"
}
###
@ruleId={{create_rule.response.body.$.ID}}
###
GET {{baseUrl}}/rules/Attributes?$filter=entity_name eq 'A_AddressEmailAddress'
###
POST {{baseUrl}}/rules/Conditions
Accept-Language: de
Content-Type: application/json


{
    "operator":"STARTS WITH",
    "value":"info@",
    "rule_ID":"d68d7091-e3f5-47ba-8e7b-cff8b2df099e",
    "attribute_name":"EmailAddress"
    
}
###

###
POST {{baseUrl}}/rules/Actions
Accept-Language: de
Content-Type: application/json


{
    "operator":"=",
    "value":"true",
    "rule_ID":"d68d7091-e3f5-47ba-8e7b-cff8b2df099e",
    "attribute_name":"IsDefaultEmailAddress"
   
}
###

GET {{baseUrl}}/rules/Violations

###
POST {{baseUrl}}/rules/getViolations
Content-Type: application/json

    {
        "ruleID":"6de2705e-491f-46e3-b157-e8203961449a"
    }
###
POST {{baseUrl}}/rules/getSelects
Content-Type: application/json

{
    "ruleID":"{{ruleId}}"

}
###
# @name getRecord
GET {{baseUrl}}/rules/Records?$filter=ID eq '751ecdcf-0ae3-4962-99ed-d9ca366fadb1'

###
@record={{getRecord.response.body.$.value[0].ID}}

###
GET {{baseUrl}}/rules/Attributes?$filter=type eq 'number' 
###
GET {{baseUrl}}/rules/Attributes?$filter=name eq 'BusinessPartner'
###
GET {{baseUrl}}/rules/Elements?$filter=record_ID eq 'd2b9c344-9bca-457f-89cb-69f1f76e6a6d'
###
PUT {{baseUrl}}/rule/Rules('8d1bfd54-de48-44ca-9244-3e2575b99046')
Content-Type: application/json

{
    
    "entity_service_name":"SalesOrderService"


}

###
PUT {{baseUrl}}/rules/Conditions('3791acbe-1b1e-46fd-b1cf-e3650bc3a4f9')
Content-Type: application/json

{
    "attribute_name":"AccountingDocExternalReference"
}

###
GET {{baseUrl}}/rules/Records
###
GET {{baseUrl}}/rules/Elements?$filter=record_ID eq '296143e1-353b-4fac-baa1-0dcc86f221ad' 

###
PUT {{baseUrl}}/rules/Rules('3791acbe-1b1e-46fd-b1cf-e3650bc3a4f9')
Content-Type: application/json

{
     "entity_service_name":"SalesOrderService"
}
###
GET {{baseUrl}}/rules/Attributes?$filter=entity_name eq 'A_AddressHomePageURL'
###
GET {{baseUrl}}/rules/Attributes?$filter=name eq 'AccountingDocExternalReference'

###
GET {{baseUrl}}/rules/Rules('1da0bcd7-9a65-4cf5-b709-6a6a8d994226')?$expand=Actions

###
GET {{baseUrl}}/rules/Rules?$expand=Conditions